kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: camunda-engine-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-file-gold
  volumeMode: Filesystem